title: Code Playground
name: Adithya Bhat
email: adithyabhat17.ab@gmail.com
description: This repository will house several code snippets and useful resources for Data Structures, Algorithms and Object-Oriented Concepts.

theme: jekyll-theme-cayman

display_footer: none
